 apiVersion: v1
 kind: ConfigMap
 metadata:
   namespace: ${METALLB_NAMESPACE}
   name: config
 data:
   config: |
     address-pools:
     - name: default
       protocol: layer2
       addresses:
       - ${INGRESS_RANGE}
